gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 6
  showFileTree: false
  showIcons: true
  theme:
    activeBorderColor:
      - bold
      - '#ffffff'
    inactiveBorderColor:
      - '#777777'
