gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
  nerdFontsVersion: 3
  showFileTree: false
  showIcons: true
  theme:
    activeBorderColor:
      - bold
      - '#ffffff'
    inactiveBorderColor:
      - '#777777'
