" Disable Vi compatibility
set nocompatible

" Map <Space> as <Leader>
let mapleader=' '

" Enable mouse
set mouse=a

" vim-plug
call plug#begin()

Plug 'metalelf0/base16-black-metal-scheme'
Plug 'rakr/vim-one'
Plug 'tpope/vim-commentary'
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'preservim/tagbar'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'dense-analysis/ale'
Plug 'mattn/emmet-vim'
Plug 'kshenoy/vim-signature'
" fzf
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" vim-airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Writing mode
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

" Backup files
set backupdir=.backup/,~/.backup/,/tmp//
set directory=.swp/,~/.swp/,/tmp//
set undodir=.undo/,~/.undo/,/tmp//

" Buffers
nnoremap <Leader>w :bdelete<CR>
nnoremap <Leader>] :bnext<CR>
nnoremap <Leader>[ :bprevious<CR>
nnoremap <Leader>t :enew<CR>

" Colors
colorscheme base16-black-metal-bathory
" colorscheme one
set background=dark
"set background=light
set termguicolors

" Comments
nnoremap <Leader>/ :Commentary<CR>

" Editing
set autoread
set backspace=eol,indent,start
set confirm
set noexpandtab
set scrolloff=5
set sidescrolloff=5
set shiftwidth=4
set tabstop=4
nmap <A-Down> ddp
nmap <A-Up> ddkP
vmap <A-Down> xkP`[V`]
vmap <A-Up> xp`[V`]

" File explorer
let g:NERDTreeWinPos='right'
let g:NERDTreeDirArrowExpandable=''
let g:NERDTreeDirArrowCollapsible=''
nnoremap <Leader>n :NERDTreeToggle<CR>
nnoremap <Leader>o :NERDTreeFind<CR>
nnoremap <Leader>c :TagbarToggle<CR>

" Layout
highlight VertSplit guibg=NONE guifg=#111111
set colorcolumn=+1
set cursorline
set fillchars+=vert:\│
set listchars=""
" set listchars+=eol:↵
" set listchars+=eol:¬
" set listchars+=extends:>
set listchars+=nbsp:␣
" set listchars+=nbsp:+
" set listchars+=precedes:<
set listchars+=tab:→\ 
" set listchars+=tab:▸\ 
set listchars+=trail:·
set list
set number
set showcmd
set splitbelow
set splitright
set textwidth=80

" Search
set hlsearch
set ignorecase
set incsearch
set smartcase
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>f :Rg<CR>
nnoremap <Leader>g :Rg<Space>
nnoremap <Leader>h :History<CR>
nnoremap <Leader>k :Rg<Space><C-R><C-W><CR>
nnoremap <Leader>l :nohlsearch<CR>
nnoremap <Leader>p :Files<CR>

" Spelling
autocmd FileType markdown setlocal spell
autocmd FileType gitcommit setlocal spell
nnoremap <Leader>s :setlocal spell!<CR>
" Autocomplete with dictionary words when spell-check is enabled
set complete+=kspell

" Status
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#buffers_label=''
let g:airline#extensions#tabline#formatter='unique_tail'
let g:airline_theme='base16_black_metal_bathory'

" Writing
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!
nnoremap <Leader>z :Goyo<CR>

" Linting
let g:airline#extensions#ale#enabled=1
let g:ale_completion_enabled=1
let g:ale_fix_on_save=1
let g:ale_fixers={ 'javascript': ['eslint', 'prettier'] }
let g:ale_lint_on_enter=0
let g:ale_lint_on_save=1
let g:ale_sign_error='●'
let g:ale_sign_warning='⚠️'
