[env]
TERM = "xterm-256color"

[colors.primary]
background = "#282c34"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window.dimensions]
columns = 140
lines = 80

[window.padding]
x = 8
y = 8

[keyboard]
bindings = [
	# tmux
	{ chars = "\u00011", key = "Key1", mods = "Command" },
	{ chars = "\u00012", key = "Key2", mods = "Command" },
	{ chars = "\u00013", key = "Key3", mods = "Command" },
	{ chars = "\u00014", key = "Key4", mods = "Command" },
	{ chars = "\u00015", key = "Key5", mods = "Command" },
	{ chars = "\u00016", key = "Key6", mods = "Command" },
	{ chars = "\u0001c", key = "T", mods = "Command" },
	{ chars = "\u0001x", key = "W", mods = "Command" },
	{ chars = "\u0001p", key = "LBracket", mods = "Command" },
	{ chars = "\u0001n", key = "RBracket", mods = "Command" },
	{ chars = "\u0001)", key = "Tab", mods = "Control" },
	{ chars = "\u0001(", key = "Tab", mods = "Control|Shift" },
]
